using NPC_Library.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NPC_Library.Occupations
{
    public static class OccupationSkillLists
    {
        public static List<Skills> Accountant = new List<Skills>() { Skills.Accounting, Skills.Appraise, Skills.Library_Use, Skills.Listen, Skills.Persuade, Skills.Spot_Hidden, Skills._random, Skills._random };
        public static List<Skills> Acrobat = new List<Skills>() { Skills.Climb, Skills.Dodge, Skills.Jump, Skills.Throw, Skills.Spot_Hidden, Skills.Swim, Skills._random, Skills._random };
        public static List<Skills> Actor = new List<Skills>() { Skills.Art_Craft, Skills.Disguise, Skills.Fighting_Brawl, Skills.History, Skills.Psychology, Skills._interpersonal, Skills._interpersonal, Skills._random };
        public static List<Skills> AgencyDetective = new List<Skills>() { Skills._interpersonal, Skills.Fighting_Brawl, Skills.Firearms, Skills.Law, Skills.Library_Use, Skills.Psychology, Skills.Stealth, Skills.Track };
        public static List<Skills> Alienist = new List<Skills>() { Skills.Law, Skills.Listen, Skills.Medicine, Skills.Language_Other, Skills.Psychoanalysis, Skills.Psychology, Skills.Science_Biology, Skills.Science_Chemistry };
        public static List<Skills> AnimalTrainer = new List<Skills>() { Skills.Jump, Skills.Listen, Skills.Natural_World, Skills.Psychology, Skills.Science, Skills.Stealth, Skills.Track, Skills._random };
        public static List<Skills> Antiquarian = new List<Skills>() { Skills.Appraise, Skills.Art_Craft, Skills.History, Skills.Library_Use, Skills.Language_Other, Skills._interpersonal, Skills.Spot_Hidden, Skills._random };
        public static List<Skills> AntiqueDealer = new List<Skills>() { Skills.Accounting, Skills.Appraise, Skills.Drive_Auto, Skills._interpersonal, Skills._interpersonal, Skills.History, Skills.Library_Use, Skills.Navigate };
        public static List<Skills> Archaeologist = new List<Skills>() { Skills.Accounting, Skills.Archaeology, Skills.Language_Other, Skills.Library_Use, Skills.Spot_Hidden, Skills.Mechanical_Repair, Skills.Navigate };
        public static List<Skills> Architect = new List<Skills>() { Skills.Accounting, Skills.Art_Craft, Skills.Law, Skills.Language_Own, Skills.Library_Use, Skills.Persuade, Skills.Psychology, Skills.Science };
        public static List<Skills> Artist = new List<Skills>() { Skills.Art_Craft, Skills.History, Skills._interpersonal, Skills.Language_Other, Skills.Psychology, Skills.Spot_Hidden, Skills._random, Skills._random };
        public static List<Skills> Asylum_Attendant = new List<Skills>() { Skills.Dodge, Skills.Fighting_Brawl, Skills.First_Aid, Skills._interpersonal, Skills._interpersonal, Skills.Listen, Skills.Psychology, Skills.Stealth };
        public static List<Skills> Athlete = new List<Skills>() { Skills.Climb, Skills.Jump, Skills.Fighting_Brawl, Skills.Ride, Skills._interpersonal, Skills.Swim, Skills.Throw, Skills._random };
        public static List<Skills> Author = new List<Skills>() { Skills.Art_Craft, Skills.History, Skills.Library_Use, Skills.Natural_World, Skills.Language_Other, Skills.Language_Own, Skills.Psychology, Skills._random };
        public static List<Skills> Bartender = new List<Skills>() { Skills.Accounting, Skills._interpersonal, Skills._interpersonal, Skills.Fighting_Brawl, Skills.Listen, Skills.Psychology, Skills.Spot_Hidden, Skills._random };
        public static List<Skills> BigGameHunter = new List<Skills>() { Skills.Firearms_Rifle_Shotgun, Skills.Spot_Hidden, Skills.Natural_World, Skills.Navigate, Skills.Science_Biology, Skills.Stealth, Skills.Track };
        public static List<Skills> BookDealer = new List<Skills>() { Skills.Accounting, Skills.Appraise, Skills.Drive_Auto, Skills.History, Skills.Library_Use, Skills.Language_Own, Skills.Language_Other, Skills._interpersonal };
        public static List<Skills> BountyHunter = new List<Skills>() { Skills.Drive_Auto, Skills.Electrical_Repair, Skills.Firearms, Skills._interpersonal, Skills.Law, Skills.Psychology, Skills.Track, Skills.Stealth };
        public static List<Skills> Boxer = new List<Skills>() { Skills.Dodge, Skills.Fighting_Brawl, Skills.Intimidate, Skills.Jump, Skills.Psychology, Skills.Spot_Hidden, Skills._random, Skills._random };
        public static List<Skills> Butler = new List<Skills>() { Skills.Accounting, Skills.Art_Craft, Skills.First_Aid, Skills.Listen, Skills.Language_Other, Skills.Psychology, Skills.Spot_Hidden, Skills._random, Skills._random };
        public static List<Skills> Clergy = new List<Skills>() { Skills.Accounting, Skills.History, Skills.Library_Use, Skills.Listen, Skills.Language_Other, Skills._interpersonal, Skills.Psychology, Skills._random };
        public static List<Skills> Cowboy = new List<Skills>() { Skills.Dodge, Skills.Firearms, Skills.First_Aid, Skills.Natural_World, Skills.Jump, Skills.Ride, Skills.Survival, Skills.Throw, Skills.Track };
        public static List<Skills> Craftsperson = new List<Skills>() { Skills.Accounting, Skills.Art_Craft, Skills.Mechanical_Repair, Skills.Natural_World, Skills.Spot_Hidden, Skills._random, Skills._random };
        public static List<Skills> Assassin = new List<Skills>() { Skills.Disguise, Skills.Electrical_Repair, Skills.Fighting_Brawl, Skills.Firearms, Skills.Locksmith, Skills.Mechanical_Repair, Skills.Stealth, Skills.Psychology };
        public static List<Skills> BankRobber = new List<Skills>() { Skills.Drive_Auto, Skills.Mechanical_Repair, Skills.Fighting_Brawl, Skills.Firearms, Skills.Intimidate, Skills.Locksmith, Skills.Operate_Heavy_Machinery, Skills._random };
        public static List<Skills> Bootlegger = new List<Skills>() { Skills.Drive_Auto, Skills.Fighting_Brawl, Skills.Firearms, Skills._interpersonal, Skills._interpersonal, Skills.Psychology, Skills.Stealth, Skills.Spot_Hidden };
        public static List<Skills> Burglar = new List<Skills>() { Skills.Appraise, Skills.Climb, Skills.Mechanical_Repair, Skills.Listen, Skills.Locksmith, Skills.Slight_Of_Hand, Skills.Stealth, Skills.Spot_Hidden };
        public static List<Skills> Conman = new List<Skills>() { Skills.Appraise, Skills.Art_Craft, Skills.Law, Skills.Listen, Skills._interpersonal, Skills._interpersonal, Skills.Psychology, Skills.Slight_Of_Hand };
        public static List<Skills> Criminal = new List<Skills>() { Skills.Disguise, Skills.Appraise, Skills.Slight_Of_Hand, Skills._interpersonal, Skills.Firearms, Skills.Locksmith, Skills.Stealth, Skills.Psychology, Skills.Spot_Hidden };
        public static List<Skills> GunMoll = new List<Skills>() { Skills.Art_Craft, Skills._interpersonal, Skills._interpersonal, Skills.Firearms_Handgun, Skills.Drive_Auto, Skills.Listen, Skills.Stealth, Skills._random };
        public static List<Skills> Fence = new List<Skills>() { Skills.Accounting, Skills.Appraise, Skills.Art_Craft, Skills.History, Skills._interpersonal, Skills.Library_Use, Skills.Spot_Hidden, Skills._random };
        public static List<Skills> Forger = new List<Skills>() { Skills.Accounting, Skills.Appraise, Skills.Art_Craft, Skills.History, Skills.Slight_Of_Hand, Skills._random };
        public static List<Skills> Smuggler = new List<Skills>() { Skills.Firearms, Skills.Listen, Skills.Navigate, Skills._interpersonal, Skills.Drive_Auto, Skills.Psychology, Skills.Slight_Of_Hand, Skills.Spot_Hidden };
        public static List<Skills> CultLeader = new List<Skills>() { Skills.Accounting, Skills._interpersonal, Skills._interpersonal, Skills.Occult, Skills.Psychology, Skills.Spot_Hidden, Skills._random, Skills._random };
        public static List<Skills> Designer = new List<Skills>() { Skills.Accounting, Skills.Art_Craft, Skills.Library_Use, Skills.Mechanical_Repair, Skills.Psychology, Skills.Spot_Hidden, Skills._random, Skills._random };
        public static List<Skills> Dilettante = new List<Skills>() { Skills.Art_Craft, Skills.Firearms, Skills.Language_Other, Skills.Ride, Skills._interpersonal, Skills._random, Skills._random, Skills._random };
        public static List<Skills> Diver = new List<Skills>() { Skills.Diving, Skills.First_Aid, Skills.Mechanical_Repair, Skills.Pilot, Skills.Science_Biology, Skills.Spot_Hidden, Skills.Swim, Skills._random };
        public static List<Skills> DoctorOfMedicine = new List<Skills>() { Skills.First_Aid, Skills.Medicine, Skills.Language_Other, Skills.Psychology, Skills.Science_Biology, Skills.Science, Skills._random, Skills._random };
        public static List<Skills> Drifter = new List<Skills>() { Skills.Climb, Skills.Jump, Skills.Listen, Skills.Navigate, Skills._interpersonal, Skills.Stealth, Skills._random, Skills._random };
        public static List<Skills> Driver = new List<Skills>() { Skills.Drive_Auto, Skills._interpersonal, Skills._interpersonal, Skills.Listen, Skills.Mechanical_Repair, Skills.Navigate, Skills.Spot_Hidden, Skills._random };
        public static List<Skills> Editor = new List<Skills>() { Skills.Accounting, Skills.History, Skills.Language_Own, Skills.Spot_Hidden, Skills._interpersonal, Skills._interpersonal, Skills.Psychology, Skills.Spot_Hidden, Skills._random };
        public static List<Skills> ElectedOfficial = new List<Skills>() { Skills.Charm, Skills.History, Skills.Intimidate, Skills.Fast_Talk, Skills.Listen, Skills.Language_Own, Skills.Persuade, Skills.Psychology };
        public static List<Skills> Engineer = new List<Skills>() { Skills.Art_Craft, Skills.Electrical_Repair, Skills.Library_Use, Skills.Mechanical_Repair, Skills.Science_Physics, Skills.Science, Skills._random };
        public static List<Skills> Entertainer = new List<Skills>() { Skills.Art_Craft, Skills.Disguise, Skills._interpersonal, Skills._interpersonal, Skills.Listen, Skills.Psychology, Skills._random, Skills._random };
        public static List<Skills> Explorer = new List<Skills>() { Skills.Climb, Skills.Firearms, Skills.History, Skills.Jump, Skills.Natural_World, Skills.Navigate, Skills.Language_Other, Skills.Survival };
        public static List<Skills> Farmer = new List<Skills>() { Skills.Art_Craft, Skills.Drive_Auto, Skills._interpersonal, Skills.Mechanical_Repair, Skills.Natural_World, Skills.Operate_Heavy_Machinery, Skills.Track, Skills._random };
        public static List<Skills> FederalAgent = new List<Skills>() { Skills.Drive_Auto, Skills.Fighting_Brawl, Skills.Firearms, Skills.Law, Skills.Persuade, Skills.Stealth, Skills.Spot_Hidden, Skills._random };
        public static List<Skills> Firefighter = new List<Skills>() { Skills.Climb, Skills.Dodge, Skills.Drive_Auto, Skills.First_Aid, Skills.Jump, Skills.Mechanical_Repair, Skills.Operate_Heavy_Machinery, Skills.Throw };
        public static List<Skills> ForeignCorrespondant = new List<Skills>() { Skills.History, Skills.Language_Other, Skills.Language_Own, Skills.Listen, Skills._interpersonal, Skills._interpersonal, Skills.Psychology, Skills._random };
        public static List<Skills> ForensicSurgeon = new List<Skills>() { Skills.Language_Other, Skills.Library_Use, Skills.Medicine, Skills.Persuade, Skills.Science_Biology, Skills.Science, Skills.Spot_Hidden };
        public static List<Skills> Gambler = new List<Skills>() { Skills.Accounting, Skills.Art_Craft, Skills._interpersonal, Skills._interpersonal, Skills.Listen, Skills.Psychology, Skills.Slight_Of_Hand, Skills.Spot_Hidden };
        public static List<Skills> Gangster = new List<Skills>() { Skills.Fighting_Brawl, Skills.Firearms, Skills.Law, Skills.Listen, Skills._interpersonal, Skills._interpersonal, Skills.Psychology, Skills.Spot_Hidden };
        public static List<Skills> Gentleman = new List<Skills>() { Skills.Art_Craft, Skills._interpersonal, Skills._interpersonal, Skills.Firearms_Rifle_Shotgun, Skills.History, Skills.Language_Other, Skills.Navigate, Skills.Ride };
        public static List<Skills> Hobo = new List<Skills>() { Skills.Art_Craft, Skills.Climb, Skills.Jump, Skills.Listen, Skills.Slight_Of_Hand, Skills.Navigate, Skills.Stealth, Skills._random };
        public static List<Skills> HospitalOrderly = new List<Skills>() { Skills.Electrical_Repair, Skills._interpersonal, Skills.Fighting_Brawl, Skills.First_Aid, Skills.Listen, Skills.Mechanical_Repair, Skills.Psychology, Skills.Stealth };
        public static List<Skills> Journalist = new List<Skills>() { Skills.Art_Craft, Skills._interpersonal, Skills.History, Skills.Library_Use, Skills.Language_Own, Skills.Psychology, Skills._random, Skills._random };
        public static List<Skills> Judge = new List<Skills>() { Skills.History, Skills.Intimidate, Skills.Law, Skills.Library_Use, Skills.Listen, Skills.Language_Own, Skills.Persuade, Skills.Psychology };
        public static List<Skills> Laboratory_Assistant = new List<Skills>() { Skills.Library_Use, Skills.Electrical_Repair, Skills.Language_Other, Skills.Science_Chemistry, Skills.Science_Biology, Skills.Science, Skills.Spot_Hidden, Skills._random };
        public static List<Skills> Laborer = new List<Skills>() { Skills.Drive_Auto, Skills.Electrical_Repair, Skills.Fighting_Brawl, Skills.First_Aid, Skills.Mechanical_Repair, Skills.Operate_Heavy_Machinery, Skills.Throw, Skills._random };
        public static List<Skills> Lumberjack = new List<Skills>() { Skills.Climb, Skills.Dodge, Skills.Fighting_Brawl, Skills.First_Aid, Skills.Jump, Skills.Mechanical_Repair, Skills.Natural_World, Skills.Throw };
        public static List<Skills> Miner = new List<Skills>() { Skills.Climb, Skills.Science, Skills.Jump, Skills.Mechanical_Repair, Skills.Operate_Heavy_Machinery, Skills.Stealth, Skills.Spot_Hidden, Skills._random };
        public static List<Skills> Lawyer = new List<Skills>() { Skills.Accounting, Skills.Law, Skills.Library_Use, Skills._interpersonal, Skills._interpersonal, Skills.Psychology, Skills._random, Skills._random };
        public static List<Skills> Librarian = new List<Skills>() { Skills.Accounting, Skills.Library_Use, Skills.Language_Other, Skills.Language_Own, Skills._random, Skills._random, Skills._random, Skills._random };
        public static List<Skills> Mechanic = new List<Skills>() { Skills.Art_Craft, Skills.Climb, Skills.Drive_Auto, Skills.Electrical_Repair, Skills.Mechanical_Repair, Skills.Operate_Heavy_Machinery, Skills._random, Skills._random };
        public static List<Skills> MilitaryOfficer = new List<Skills>() { Skills.Accounting, Skills.Firearms, Skills.Navigate, Skills.First_Aid, Skills._interpersonal, Skills._interpersonal, Skills.Psychology, Skills._random };
        public static List<Skills> Missionary = new List<Skills>() { Skills.Art_Craft, Skills.First_Aid, Skills.Mechanical_Repair, Skills.Medicine, Skills.Natural_World, Skills._interpersonal, Skills._random, Skills._random };
        public static List<Skills> MountainClimber = new List<Skills>() { Skills.Climb, Skills.First_Aid, Skills.Jump, Skills.Listen, Skills.Navigate, Skills.Language_Other, Skills.Survival, Skills.Track };
        public static List<Skills> MuseumCurator = new List<Skills>() { Skills.Accounting, Skills.Appraise, Skills.Archaeology, Skills.History, Skills.Library_Use, Skills.Spot_Hidden };
        public static List<Skills> Musician = new List<Skills>() { Skills.Art_Craft, Skills._interpersonal, Skills.Listen, Skills.Psychology, Skills._random, Skills._random, Skills._random, Skills._random };
        public static List<Skills> Nurse = new List<Skills>() { Skills.First_Aid, Skills.Listen, Skills.Medicine, Skills._interpersonal, Skills.Psychology, Skills.Science_Biology, Skills.Science_Chemistry, Skills.Spot_Hidden };
        public static List<Skills> Occultist = new List<Skills>() { Skills.Anthropology, Skills.History, Skills.Library_Use, Skills._interpersonal, Skills.Occult, Skills.Language_Other, Skills.Science, Skills._random };
        public static List<Skills> Outdoorsman = new List<Skills>() { Skills.Firearms, Skills.First_Aid, Skills.Listen, Skills.Natural_World, Skills.Navigate, Skills.Spot_Hidden, Skills.Survival, Skills.Track };
        public static List<Skills> Parapsychologist = new List<Skills>() { Skills.Anthropology, Skills.Art_Craft, Skills.History, Skills.Library_Use, Skills.Occult, Skills.Language_Other, Skills.Psychology, Skills._random };
        public static List<Skills> Pharmacist = new List<Skills>() { Skills.Accounting, Skills.First_Aid, Skills.Language_Other, Skills.Library_Use, Skills._interpersonal, Skills.Psychology, Skills.Science_Chemistry, Skills.Science };
        public static List<Skills> Photographer = new List<Skills>() { Skills.Art_Craft, Skills._interpersonal, Skills.Psychology, Skills.Science_Chemistry, Skills.Stealth, Skills.Spot_Hidden, Skills._random, Skills._random };
        public static List<Skills> Pilot = new List<Skills>() { Skills.Electrical_Repair, Skills.Mechanical_Repair, Skills.Navigate, Skills.Operate_Heavy_Machinery, Skills.Pilot, Skills.Science_Physics, Skills._random, Skills._random };
        public static List<Skills> Police_Detective = new List<Skills>() { Skills.Art_Craft, Skills.Disguise, Skills.Firearms, Skills.Law, Skills.Listen, Skills._interpersonal, Skills.Psychology, Skills.Spot_Hidden, Skills._random };
        public static List<Skills> PrivateInvestigator = new List<Skills>() { Skills.Art_Craft, Skills.Disguise, Skills.Law, Skills.Library_Use, Skills._interpersonal, Skills.Psychology, Skills.Spot_Hidden, Skills._random };
        public static List<Skills> Professor = new List<Skills>() { Skills.Library_Use, Skills.Language_Other, Skills.Language_Own, Skills.Psychology, Skills._random, Skills._random, Skills._random, Skills._random };
        public static List<Skills> Prospector = new List<Skills>() { Skills.Climb, Skills.First_Aid, Skills.History, Skills.Mechanical_Repair, Skills.Navigate, Skills.Science, Skills.Spot_Hidden, Skills._random };
        public static List<Skills> Prostitute = new List<Skills>() { Skills.Art_Craft, Skills._interpersonal, Skills._interpersonal, Skills.Dodge, Skills.Psychology, Skills.Slight_Of_Hand, Skills.Stealth, Skills._random };
        public static List<Skills> Psychiatrist = new List<Skills>() { Skills.Language_Other, Skills.Listen, Skills.Medicine, Skills.Persuade, Skills.Psychoanalysis, Skills.Psychology, Skills.Science_Biology, Skills.Science_Chemistry };
        public static List<Skills> Psychologist = new List<Skills>() { Skills.Accounting, Skills.Library_Use, Skills.Listen, Skills.Persuade, Skills.Psychoanalysis, Skills.Psychology, Skills._random, Skills._random };
        public static List<Skills> Researcher = new List<Skills>() { Skills.History, Skills.Library_Use, Skills._interpersonal, Skills.Language_Other, Skills.Spot_Hidden, Skills._random, Skills._random, Skills._random };
        public static List<Skills> Sailor = new List<Skills>() { Skills.First_Aid, Skills.Mechanical_Repair, Skills.Natural_World, Skills.Navigate, Skills._interpersonal, Skills.Pilot, Skills.Spot_Hidden, Skills.Swim };
        public static List<Skills> Salesperson = new List<Skills>() { Skills.Accounting, Skills._interpersonal, Skills._interpersonal, Skills.Drive_Auto, Skills.Listen, Skills.Psychology, Skills.Stealth, Skills.Slight_Of_Hand, Skills._random };
        public static List<Skills> Scientist = new List<Skills>() { Skills.Library_Use, Skills.Language_Other, Skills.Language_Own, Skills._interpersonal, Skills.Spot_Hidden, Skills.Science_Biology, Skills.Science_Chemistry, Skills.Science_Physics };
        public static List<Skills> Secretary = new List<Skills>() { Skills.Accounting, Skills.Art_Craft, Skills._interpersonal, Skills._interpersonal, Skills.Language_Own, Skills.Library_Use, Skills.Psychology, Skills._random };
        public static List<Skills> Shopkeeper = new List<Skills>() { Skills.Accounting, Skills._interpersonal, Skills._interpersonal, Skills.Electrical_Repair, Skills.Listen, Skills.Mechanical_Repair, Skills.Psychology, Skills.Spot_Hidden };
        public static List<Skills> Soldier = new List<Skills>() { Skills.Climb, Skills.Dodge, Skills.Fighting_Brawl, Skills.Firearms, Skills.Stealth, Skills.Survival, Skills.First_Aid, Skills.Mechanical_Repair };
        public static List<Skills> Spy = new List<Skills>() { Skills.Disguise, Skills.Firearms, Skills.Listen, Skills.Language_Other, Skills._interpersonal, Skills.Psychology, Skills.Slight_Of_Hand, Skills.Stealth };
        public static List<Skills> Student = new List<Skills>() { Skills.Language_Other, Skills.Library_Use, Skills.Listen, Skills._random, Skills._random, Skills._random, Skills._random, Skills._random };
        public static List<Skills> Stuntman = new List<Skills>() { Skills.Climb, Skills.Dodge, Skills.Electrical_Repair, Skills.Fighting_Brawl, Skills.First_Aid, Skills.Jump, Skills.Swim, Skills.Drive_Auto };
        public static List<Skills> TribeMember = new List<Skills>() { Skills.Climb, Skills.Fighting_Brawl, Skills.Listen, Skills.Natural_World, Skills.Occult, Skills.Spot_Hidden, Skills.Swim, Skills.Survival };
        public static List<Skills> Undertaker = new List<Skills>() { Skills.Accounting, Skills.Drive_Auto, Skills._interpersonal, Skills.History, Skills.Occult, Skills.Psychology, Skills.Science_Biology, Skills.Science_Chemistry };
        public static List<Skills> UnionActivist = new List<Skills>() { Skills.Accounting, Skills._interpersonal, Skills._interpersonal, Skills.Fighting_Brawl, Skills.Law, Skills.Listen, Skills.Operate_Heavy_Machinery, Skills.Psychology };
        public static List<Skills> Waiter = new List<Skills>() { Skills.Accounting, Skills.Art_Craft, Skills.Dodge, Skills.Listen, Skills._interpersonal, Skills._interpersonal, Skills.Psychology, Skills._random };
        public static List<Skills> WhiteCollarWorker = new List<Skills>() { Skills.Accounting, Skills.Language_Own, Skills.Law, Skills.Library_Use, Skills.Listen, Skills._interpersonal, Skills._random, Skills._random };
        public static List<Skills> Zealot = new List<Skills>() { Skills.History, Skills._interpersonal, Skills._interpersonal, Skills.Psychology, Skills.Stealth, Skills._random, Skills._random, Skills._random };
        public static List<Skills> Zookeeper = new List<Skills>() { Skills.Art_Craft, Skills.Accounting, Skills.Dodge, Skills.First_Aid, Skills.Natural_World, Skills.Medicine, Skills.Science, Skills.Science_Biology };
               
    }
}
